config/routes.rb
Rails.application.routes.draw do
  resources :classificacoes
  resources :generos
  resources :avaliacaos
  resources :jogos
  resources :classificacaos
  resources :categoria
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genero.rb
class Genero < ApplicationRecord
    validates :nome, presence: true
    validates :nome, uniqueness: true
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  before_action :set_genero, only: [:show, :edit, :update, :destroy]

  # GET /generos
  # GET /generos.json
  def index
    @generos = Genero.all
  end

  # GET /generos/1
  # GET /generos/1.json
  def show
  end

  # GET /generos/new
  def new
    @genero = Genero.new
  end

  # GET /generos/1/edit
  def edit
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(genero_params)

    respond_to do |format|
      if @genero.save
        format.html { redirect_to @genero, notice: 'Genero was successfully created.' }
        format.json { render :show, status: :created, location: @genero }
      else
        format.html { render :new }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generos/1
  # PATCH/PUT /generos/1.json
  def update
    respond_to do |format|
      if @genero.update(genero_params)
        format.html { redirect_to @genero, notice: 'Genero was successfully updated.' }
        format.json { render :show, status: :ok, location: @genero }
      else
        format.html { render :edit }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    @genero.destroy
    respond_to do |format|
      format.html { redirect_to generos_url, notice: 'Genero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genero_params
      params.require(:genero).permit(:nome)
    end
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/generos/_form.html.erb
<%= form_with(model: genero, local: true) do |form| %>
  <% if genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genero.errors.count, "error") %> prohibited this genero from being saved:</h2>

      <ul>
      <% genero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/generos/edit.html.erb
<h1>Editing Genero</h1>

<%= render 'form', genero: @genero %>

<%= link_to 'Show', @genero %> |
<%= link_to 'Back', generos_path %>

app/views/generos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generos.each do |genero| %>
      <tr>
        <td><%= genero.nome %></td>
        <td><%= link_to 'Show', genero %></td>
        <td><%= link_to 'Edit', edit_genero_path(genero) %></td>
        <td><%= link_to 'Destroy', genero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genero', new_genero_path %>

app/views/generos/new.html.erb
<h1>New Genero</h1>

<%= render 'form', genero: @genero %>

<%= link_to 'Back', generos_path %>

app/views/generos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @genero.nome %>
</p>

<%= link_to 'Edit', edit_genero_path(@genero) %> |
<%= link_to 'Back', generos_path %>