config/routes.rb
Rails.application.routes.draw do
  resources :classificacoes
  resources :generos
  resources :avaliacaos
  resources :jogos
  resources :classificacaos
  resources :categoria
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/classificacoes_controller.rb
class ClassificacoesController < ApplicationController
  before_action :set_classificacao, only: [:show, :edit, :update, :destroy]

  # GET /classificacoes
  # GET /classificacoes.json
  def index
    @classificacoes = Classificacao.all
  end

  # GET /classificacoes/1
  # GET /classificacoes/1.json
  def show
  end

  # GET /classificacoes/new
  def new
    @classificacao = Classificacao.new
  end

  # GET /classificacoes/1/edit
  def edit
  end

  # POST /classificacoes
  # POST /classificacoes.json
  def create
    @classificacao = Classificacao.new(classificacao_params)

    respond_to do |format|
      if @classificacao.save
        format.html { redirect_to @classificacao, notice: 'Classificacao was successfully created.' }
        format.json { render :show, status: :created, location: @classificacao }
      else
        format.html { render :new }
        format.json { render json: @classificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classificacoes/1
  # PATCH/PUT /classificacoes/1.json
  def update
    respond_to do |format|
      if @classificacao.update(classificacao_params)
        format.html { redirect_to @classificacao, notice: 'Classificacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @classificacao }
      else
        format.html { render :edit }
        format.json { render json: @classificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classificacoes/1
  # DELETE /classificacoes/1.json
  def destroy
    @classificacao.destroy
    respond_to do |format|
      format.html { redirect_to classificacoes_url, notice: 'Classificacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classificacao
      @classificacao = Classificacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classificacao_params
      params.require(:classificacao).permit(:nome, :idade_minima)
    end
end

app/helpers/classificacoes_helper.rb
module ClassificacoesHelper
end

app/views/classificacoes/_form.html.erb
<%= form_with(model: classificacao, local: true) do |form| %>
  <% if classificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classificacao.errors.count, "error") %> prohibited this classificacao from being saved:</h2>

      <ul>
      <% classificacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :idade_minima %>
    <%= form.number_field :idade_minima %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classificacoes/edit.html.erb
<h1>Editing Classificacao</h1>

<%= render 'form', classificacao: @classificacao %>

<%= link_to 'Show', @classificacao %> |
<%= link_to 'Back', classificacoes_path %>

app/views/classificacoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classificacoes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade minima</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classificacoes.each do |classificacao| %>
      <tr>
        <td><%= classificacao.nome %></td>
        <td><%= classificacao.idade_minima %></td>
        <td><%= link_to 'Show', classificacao %></td>
        <td><%= link_to 'Edit', edit_classificacao_path(classificacao) %></td>
        <td><%= link_to 'Destroy', classificacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classificacao', new_classificacao_path %>

app/views/classificacoes/new.html.erb
<h1>New Classificacao</h1>

<%= render 'form', classificacao: @classificacao %>

<%= link_to 'Back', classificacoes_path %>

app/views/classificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @classificacao.nome %>
</p>

<p>
  <strong>Idade minima:</strong>
  <%= @classificacao.idade_minima %>
</p>

<%= link_to 'Edit', edit_classificacao_path(@classificacao) %> |
<%= link_to 'Back', classificacoes_path %>