config/routes.rb
Rails.application.routes.draw do
  resources :classificacoes
  resources :generos
  resources :avaliacaos
  resources :jogos
  resources :classificacaos
  resources :categoria
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jogo.rb
class Jogo < ApplicationRecord

    belongs_to :classificacao

    validates :titulo, :desenvolvedora, :descricao, :lancamento, presence: true

    scope:por_titulo, lambda {|titulo = nil|
        
            where(titulo: titulo) if titulo
        
    }
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :set_jogo, only: [:show, :edit, :update, :destroy]

  # GET /jogos
  # GET /jogos.json
  def index   
      @jogos = Jogo.por_titulo(params[:titulo])    
  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
  end

  # GET /jogos/new
  def new
    @jogo = Jogo.new
  end

  # GET /jogos/1/edit
  def edit
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(jogo_params)

    respond_to do |format|
      if @jogo.save
        format.html { redirect_to action: :index, notice: 'Jogo was successfully created.' }
        format.json { render :show, status: :created, location: @jogo }
      else
        format.html { render :new }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogos/1
  # PATCH/PUT /jogos/1.json
  def update
    respond_to do |format|
      if @jogo.update(jogo_params)
        format.html { redirect_to @jogo, notice: 'Jogo was successfully updated.' }
        format.json { render :show, status: :ok, location: @jogo }
      else
        format.html { render :edit }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    @jogo.destroy
    respond_to do |format|
      format.html { redirect_to jogos_url, notice: 'Jogo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogo
      @jogo = Jogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogo_params
      params.require(:jogo).permit(:titulo,
                                   :descricao,
                                   :desenvolvedora,
                                   :lancamento, 
                                   :classificacao_id)
    end
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/views/jogos/_form.html.erb
<%= form_with(model: jogo, local: true) do |form| %>
  <% if jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
      <% jogo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label :desenvolvedora %>
    <%= form.text_field :desenvolvedora %>
  </div>

  <div class="field">
    <%= form.label :lancamento %>
    <%= form.date_select :lancamento %>
  </div>

  <div class="field">
    <%= form.label :classificacao_id %>
    <%= form.select :classificacao_id, Classificacao.all.collect {|c| [c.nome, c.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Show', @jogo %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jogos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Desenvolvedora</th>
      <th>Lancamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogos.each do |jogo| %>
      <tr>
        <td><%= jogo.titulo %></td>
        <td><%= jogo.descricao %></td>
        <td><%= jogo.desenvolvedora %></td>
        <td><%= jogo.lancamento %></td>
        <td><%= link_to 'Show', jogo %></td>
        <td><%= link_to 'Edit', edit_jogo_path(jogo) %></td>
        <td><%= link_to 'Destroy', jogo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jogo', new_jogo_path %>

app/views/jogos/new.html.erb
<h1>New Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Back', jogos_path %>

app/views/jogos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @jogo.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @jogo.descricao %>
</p>

<p>
  <strong>Desenvolvedora:</strong>
  <%= @jogo.desenvolvedora %>
</p>

<p>
  <strong>Lancamento:</strong>
  <%= @jogo.lancamento %>
</p>

<%= link_to 'Edit', edit_jogo_path(@jogo) %> |
<%= link_to 'Back', jogos_path %>